// Curated figlet fonts. Each font loads on demand (one dynamic import per font).
export type Category = "Blocky" | "3D" | "Slant" | "Script" | "Compact" | "Retro" | "Cyber" | "Banner";
export type FontMeta = { name: string; tags: Category[] };

export const CATEGORIES: Category[] = ["Blocky", "3D", "Slant", "Script", "Compact", "Retro", "Cyber", "Banner"];
export const TOTAL_FIGLET_FONTS = 335;
export const DEFAULT_FONT = "ANSI Shadow";

export const FONTS: FontMeta[] = [
  { name: "ANSI Shadow", tags: ["Blocky", "Retro"] },
  { name: "Colossal", tags: ["Blocky"] },
  { name: "Block", tags: ["Blocky", "Retro"] },
  { name: "Banner3", tags: ["Banner", "Blocky"] },
  { name: "Univers", tags: ["Blocky"] },
  { name: "DOS Rebel", tags: ["Blocky", "Retro"] },
  { name: "Delta Corps Priest 1", tags: ["Blocky", "Retro"] },
  { name: "Larry 3D", tags: ["3D"] },
  { name: "Isometric1", tags: ["3D"] },
  { name: "Shadow", tags: ["3D"] },
  { name: "Slant", tags: ["Slant"] },
  { name: "Small Slant", tags: ["Slant", "Compact"] },
  { name: "Speed", tags: ["Slant"] },
  { name: "Lean", tags: ["Slant"] },
  { name: "Script", tags: ["Script"] },
  { name: "Graceful", tags: ["Script"] },
  { name: "Sweet", tags: ["Script"] },
  { name: "Small", tags: ["Compact"] },
  { name: "Mini", tags: ["Compact"] },
  { name: "Thin", tags: ["Compact"] },
  { name: "Rectangles", tags: ["Compact"] },
  { name: "Chunky", tags: ["Compact"] },
  { name: "Crawford", tags: ["Compact"] },
  { name: "Bubble", tags: ["Compact"] },
  { name: "Doom", tags: ["Retro"] },
  { name: "Epic", tags: ["Retro"] },
  { name: "Bloody", tags: ["Retro"] },
  { name: "Star Wars", tags: ["Retro"] },
  { name: "Elite", tags: ["Retro"] },
  { name: "Bulbhead", tags: ["Retro"] },
  { name: "Graffiti", tags: ["Retro"] },
  { name: "Sub-Zero", tags: ["Retro"] },
  { name: "Roman", tags: ["Retro"] },
  { name: "Poison", tags: ["Retro"] },
  { name: "Cyberlarge", tags: ["Cyber"] },
  { name: "Cybermedium", tags: ["Cyber", "Compact"] },
  { name: "Calvin S", tags: ["Compact", "Retro"] },
  { name: "Standard", tags: ["Banner"] },
  { name: "Big", tags: ["Banner"] },
  { name: "Rounded", tags: ["Banner"] },
  { name: "Ogre", tags: ["Banner"] },
];

type FontModule = { default: string };

export const FONT_LOADERS: Record<string, () => Promise<FontModule>> = {
  "ANSI Shadow": () => import("figlet/importable-fonts/ANSI Shadow.js"),
  "Colossal": () => import("figlet/importable-fonts/Colossal.js"),
  "Block": () => import("figlet/importable-fonts/Block.js"),
  "Banner3": () => import("figlet/importable-fonts/Banner3.js"),
  "Univers": () => import("figlet/importable-fonts/Univers.js"),
  "DOS Rebel": () => import("figlet/importable-fonts/DOS Rebel.js"),
  "Delta Corps Priest 1": () => import("figlet/importable-fonts/Delta Corps Priest 1.js"),
  "Larry 3D": () => import("figlet/importable-fonts/Larry 3D.js"),
  "Isometric1": () => import("figlet/importable-fonts/Isometric1.js"),
  "Shadow": () => import("figlet/importable-fonts/Shadow.js"),
  "Slant": () => import("figlet/importable-fonts/Slant.js"),
  "Small Slant": () => import("figlet/importable-fonts/Small Slant.js"),
  "Speed": () => import("figlet/importable-fonts/Speed.js"),
  "Lean": () => import("figlet/importable-fonts/Lean.js"),
  "Script": () => import("figlet/importable-fonts/Script.js"),
  "Graceful": () => import("figlet/importable-fonts/Graceful.js"),
  "Sweet": () => import("figlet/importable-fonts/Sweet.js"),
  "Small": () => import("figlet/importable-fonts/Small.js"),
  "Mini": () => import("figlet/importable-fonts/Mini.js"),
  "Thin": () => import("figlet/importable-fonts/Thin.js"),
  "Rectangles": () => import("figlet/importable-fonts/Rectangles.js"),
  "Chunky": () => import("figlet/importable-fonts/Chunky.js"),
  "Crawford": () => import("figlet/importable-fonts/Crawford.js"),
  "Bubble": () => import("figlet/importable-fonts/Bubble.js"),
  "Doom": () => import("figlet/importable-fonts/Doom.js"),
  "Epic": () => import("figlet/importable-fonts/Epic.js"),
  "Bloody": () => import("figlet/importable-fonts/Bloody.js"),
  "Star Wars": () => import("figlet/importable-fonts/Star Wars.js"),
  "Elite": () => import("figlet/importable-fonts/Elite.js"),
  "Bulbhead": () => import("figlet/importable-fonts/Bulbhead.js"),
  "Graffiti": () => import("figlet/importable-fonts/Graffiti.js"),
  "Sub-Zero": () => import("figlet/importable-fonts/Sub-Zero.js"),
  "Roman": () => import("figlet/importable-fonts/Roman.js"),
  "Poison": () => import("figlet/importable-fonts/Poison.js"),
  "Cyberlarge": () => import("figlet/importable-fonts/Cyberlarge.js"),
  "Cybermedium": () => import("figlet/importable-fonts/Cybermedium.js"),
  "Calvin S": () => import("figlet/importable-fonts/Calvin S.js"),
  "Standard": () => import("figlet/importable-fonts/Standard.js"),
  "Big": () => import("figlet/importable-fonts/Big.js"),
  "Rounded": () => import("figlet/importable-fonts/Rounded.js"),
  "Ogre": () => import("figlet/importable-fonts/Ogre.js"),
};
